# Configuración básica requerida
android.useAndroidX=true

# ¡Cámbialo a false! Si alguna librería vieja falla, sabrás cuál actualizar.
android.enableJetifier=false

# Subimos la memoria a 4GB (Cambia a -Xmx6G si tienes 16GB o más de RAM total en tu PC)
org.gradle.jvmargs=-Xmx4G -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC

# Estilo de código
kotlin.code.style=official

# === SÚPER OPTIMIZACIONES AÑADIDAS ===
# Compilación en paralelo para proyectos multi-módulo
org.gradle.parallel=true

# Activa la caché global de Gradle para reutilizar código ya compilado
org.gradle.caching=true

# Compilación incremental para Kotlin (solo compila lo que modificas)
kotlin.incremental=true
kotlin.caching.enabled=true